language: node_js

cache:
  directories:
    - node_modules

matrix:
  include:
    - node_js: "8"
    - node_js: "10"
      before_install: npm install coveralls
      before_script: npm run lint
      after_success: npm run coverage && cat ./coverage/lcov.info | coveralls lib;
    - node_js: "12"
    - node_js: "node"

git:
  depth: 10
